### ISSUE TITLE
DigitalOcean is not a constructor

### ISSUE THREAD

**Issue by ENEcycle** [matt-major/do-wrapper#16]
Hi guys,
got this issue: TypeError: DigitalOcean is not a constructor
the code is: 
```
const DigitalOcean = require("do-wrapper");
const api = new DigitalOcean("myKey", 10);
```

`const api = new DigitalOcean("myKey").default;` works

**Comment by ENEcycle** [comment]
Sorry,it is  my fault.
reason is `const DigitalOcean = require("do-wrapper");`

**Comment by goldfire** [comment]
Not your fault, the maintainer really needs a changelog to document these things.
