### ISSUE TITLE
Getting TypeError on all endpoints

### ISSUE THREAD

**Issue by drtweety** [matt-major/do-wrapper#42]
I followed the code as mentioned in the Readme:

```js
const KEY = '[KEY_HERE]';
const DigitalOcean = require('do-wrapper').default;
const api = new DigitalOcean(KEY);

api.account((err, res, body) => {
    console.log(body);
  });
```

But I get the following error for all endpoints:

```
api.accountGetActions((err, res, body) => {
    ^

TypeError: api.accountGetActions is not a function
```

**Comment by matt-major** [comment]
It seems you're using the old version there, but likely have the new v4, can you confirm which version is in your `package.json`?

If it is v4 you will need to use the new structure in this branch (which will soon be merged to `master`.

https://github.com/matt-major/do-wrapper/tree/v4-rewrite

**Comment by matt-major** [comment]
@drtweety v4 is now available, please upgrade and re-open if the issue still persists.
