### ISSUE TITLE
Version 4.0.0 is missing typings

### ISSUE THREAD

**Issue by filipproch** [matt-major/do-wrapper#44]
When I try to use latest version 4.0.0 from typescript, it complains there are no typings and suggests installing `@types/do-wrapper`.

Indeed looking into the dist folder/tsconfig.json the export of `d.ts` files is not enabled.

Any reason why?

**Comment by matt-major** [comment]
@filipproch I'll get these added and confirm when available

**Comment by matt-major** [comment]
These have been added now
