### ISSUE TITLE
droplets.deleteById throwing errors

### ISSUE THREAD

**Issue by gurupras** [matt-major/do-wrapper#46]
DO's [API documentation on deleting droplets](https://developers.digitalocean.com/documentation/v2/#delete-a-droplet) states that

> No response body will be sent back, but the response code will indicate success. Specifically, the response code will be a 204, which means that the action was successful with no returned body data.

Not sure if the API was changed recently, but this is in turn throwing errors in https://github.com/matt-major/do-wrapper/blob/9e34020463a605877baa76befddbc913735f18d9/src/request-helper.ts#L58-L60

Really love using the library

**Comment by matt-major** [comment]
@gurupras yes the API has changed in v4, I'm pulling in a fix for this now.
