### ISSUE TITLE
Are there breaking changes in v4.0.0?

### ISSUE THREAD

**Issue by menewman** [matt-major/do-wrapper#47]
(This is more of a documentation question than an "issue", but I thought maybe others might have the same question and could benefit from seeing the answer too.)

Are there any known breaking changes associated with the v4.0.0 release? There isn't a list of changes in the release on GitHub, but perhaps I'm missing release notes somewhere else:
https://github.com/matt-major/do-wrapper/releases/tag/v4.0.0

We use `do-wrapper` in a project and saw that there's a new version, so we'd like to update. However, assuming this project follows semantic versioning, the new version number implies that there are breaking changes, so we'd like to know if there's anything to look out for specifically on upgrading.

Thanks again for your hard work on this project! 🙌

**Comment by matt-major** [comment]
Hi @menewman - yes the package was entirely re-written in v4.0.0, if you take a look in `docs/index.html` and the subsequent child docs/directories, you can see all the new methods available and the structure of them.

I suppose the docs could be improved, I shall take a look when I have time.

**Comment by menewman** [comment]
Hm, so in addition to the implementation changing due to the rewrite, some of the existing methods may have changed or been removed in a way that could break existing consumers? Okay... we'll be careful about upgrading, then. Thank you for your response!

**Comment by mittalyashu** [comment]
How can I access the docs site? What is the URL?

**Comment by matt-major** [comment]
@mittalyashu auto-generated docs are here: https://github.com/matt-major/do-wrapper/tree/master/docs, I'll work on some more readable / thorough ones when I have time.

**Comment by menewman** [comment]
For anyone else who stumbles across this, here's a quick update: I finally took the time to explore what had changed between v3 and v4 of `do-wrapper`, and there were two major changes that other upgraders should also be aware of:
1. Now, methods are grouped under modules: for example, `instance.dropletsCreate` -> `instance.droplets.create`, `instance.dropletsDelete` -> `instance.droplets.deleteById`, `instance.droplets.tagsAddResources` -> `instance.droplets.tags.addResources`
2. Now, methods return the response body directly instead of returning a wrapped response with a `body` property.

For example, previously `instance.dropletsGetById` would return something like this:
```js
{ body: { droplet: { /* droplet stuff */ } } }
```
...but now, `instance.droplets.getById` will return something like this:
```js
{ droplet: { /* droplet stuff */ } }
```

These are really natural, intuitive changes that make the API more pleasant to work with -- thank you for making them, @matt-major!

The docs that can be found under `docs/` are also really helpful -- it would be lovely to have these published somewhere where they're easy to browse online, like a static GitHub Pages site. (Lazy developer confession: If I'd been able to browse these easily without cloning the repo, I probably would have upgraded a lot sooner.)

Anyway, that totally resolves my questions about breaking changes, so please feel free to close this issue if you decide you ultimately don't want to make any further documentation changes! 👍 

While testing the upgrade, I did find one issue with `tags.addResources` / `tags.removeResources` that I will write up as a separate issue.

**Comment by Jopchumba** [comment]
Sounds Great, From the discussion above the way of calling the methods or the wording convention changed by Including the (.)
which is more pleasant for It can let you understand which resources you are working on or with.
an example of why the changes will make sense  `instance.accout.Method and instance.droplet .(method)`
From the above its easy to distinguish between the account and droplets being separate resources.

**Comment by Jopchumba** [comment]
> Hi @menewman - yes the package was entirely re-written in v4.0.0, if you take a look in `docs/index.html` and the subsequent child docs/directories, you can see all the new methods available and the structure of them.
> 
> I suppose the docs could be improved, I shall take a look when I have time.

@matt-major will be able to see if we could work on the docs but the current read.me is Great but a few more examples.BTW I added an example folder with one example project on how someone can You create a CLI and work with digital Ocean resources

**Comment by Jopchumba** [comment]
> How can I access the docs site? What is the URL?

Or another workaround is a fork or clone the repo to your local system and once you have it just navigate to it and find your working directory and open it in the browser and see the docs section Hit index.html and you should be Good

**Comment by matt-major** [comment]
@Jopchumba @menewman  @mittalyashu the docs can now be found here: https://github.com/matt-major/do-wrapper/tree/master/docs and will be updated with any changes. As more typescript definitions are added these should become even more useful.
