### ISSUE TITLE
internal_server_error: Server was unable to give you a response.

### ISSUE THREAD

**Issue by falkenbach** [matt-major/do-wrapper#48]
Under version ^3.25.4 from today getting API errors:

Request
api.snapshots()

Response:
{
  id: 'internal_server_error',
  message: 'Server was unable to give you a response.'
}

Before it was working fine, now we have permanent error as above and API is unusable.

**Comment by matt-major** [comment]
@falkenbach that looks like an issue at Digital Ocean's end rather than with this library. Additionally v3 has now been superseded by v4, so I would recommend upgrading anyway.
