### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by PHClement** [matt-major/do-wrapper#5]
Hello,

I'm having an issue with the library, I'm using https with let's encrypt and nginx proxy reverse:

Screenshot of the error: [Click Here](https://gyazo.com/2a1cb582286db802c0ed324a76e862fb)

Thank you in advance,

Clément

**Comment by matt-major** [comment]
Hi @PHClement - I'd need more information about how you're trying to use NGINX / this library in order to investigate.

Can you provide any additional information?
