### ISSUE TITLE
Create snapshot of block volume

### ISSUE THREAD

**Issue by Daxcor69** [matt-major/do-wrapper#58]
I am trying to figure out how to create a snapshot of a volume.  I don't see it under volume and I don't see it under snapshot. Can you help?

**Comment by matt-major** [comment]
Hey @Daxcor69 !

Indeed looks like I missed this off (+ the list snapshots for volumes). I have added both of these in https://github.com/matt-major/do-wrapper/pull/64 which I'm just waiting for Travis CI to run through and will get it merged & published.

Thanks!
