### ISSUE TITLE
Create droplet: tags as an array

### ISSUE THREAD

**Issue by pcgrenier** [matt-major/do-wrapper#65]
https://github.com/matt-major/do-wrapper/blob/055b5c6d2e98d74d68f10aa61c26da4e7d4afcd3/dist/types/droplets.d.ts#L13

Can that be swapped to a string[]? to match the [api ](https://developers.digitalocean.com/documentation/v2/#create-a-new-droplet)

**Comment by matt-major** [comment]
@pcgrenier fixed as of 119ffc6fdef7c3f1e600edec1e42d00e4fb8cfac

Sorry for the delay in correcting this.
