### ISSUE TITLE
TypeScript typings for promises

### ISSUE THREAD

**Issue by slavikus** [matt-major/do-wrapper#8]
The included TypeScript types are missing the promise versions of all the calls, only allowing the callback ones. Is there any chance you could add these?

Thank you in advance!

**Comment by matt-major** [comment]
@slavikus I'll be re-writing all the TypeScript types / definitions as part of #35, once this is done I'll also export all the definitions for use externally.

**Comment by matt-major** [comment]
Methods now use promises only, so closing this as no longer required.
